### PR TITLE
Translation PT-BR

### PR DESCRIPTION
**Pull request by imsantosrodrigo**
Translation of words and phrases that have not yet been translated.

### CODE REVIEW

**Comment by lukaschal** [comment]
On translation or fixed in a MLCP platform.

**Comment by lukaschal** [comment]
@imsantosrodrigo Please verify and close this issue.

**Comment by imsantosrodrigo** [comment]
> @imsantosrodrigo Please verify and close this issue.

I solved the conflicts.

**Comment by imsantosrodrigo** [comment]
I solved the conflicts.

**Comment by imsantosrodrigo** [comment]
> @imsantosrodrigo Please verify and close this issue.

I solved the conflicts.

**Pull request closed without merging**
