### PR TITLE
Fix french translation vocabulary

### PR DESCRIPTION
**Pull request by Erim32**
Correct French translation, "Révéler" is incorrect, shoud be "Ouvrir"

### CODE REVIEW

**Comment by lukaschal** [comment]
On review.

Reveal in Finder | Révéler dans le Finder
Reveal in   Explorer | Révéler dans l'Explorateur
Reveal in Side   Bar | Afficher dans la barre latérale
Reveal in File Explorer | Révéler dans l'Explorateur de fichiers

**Comment by lukaschal** [comment]
No reason to change this. The source does not say "Open", but "Reveal". 1Different concept.

**Comment by Erim32** [comment]
Perhaps it is not the literal translation of the English source but in common usage and software in French. The standard is "Ouvrir dans l'explorateur" or less frequently "Voir dans l'explorateur" not "Révéler dans l'explorateur", the word "Révéler" is for something hidden. @lukaschal

**Comment by lukaschal** [comment]
Translation reflecting source text. If source text is not appropriate for software terminology, please log en-us issue.

**Pull request closed without merging**
