### PR TITLE
Add Bulgarian translation of the README.md

### PR DESCRIPTION
**Pull request by lyubomirv**

### CODE REVIEW

**Comment by danyeh** [comment]
@lyubomirv . Thank you very much! The language pack has been republished with your version of readme in it.

**Comment by lyubomirv** [comment]
@danyeh You're welcome!

**Comment by lyubomirv** [comment]
@danyeh I'm sorry, I've just noticed an error when I checked the translation in VS Code. I've immediately fixed and posted a new merge request here: https://github.com/Microsoft/vscode-loc/pull/7

**Comment by danyeh** [comment]
No worry. Thank you for the fix. Language Pack has been re-published.

**Comment by lyubomirv** [comment]
Thank you!

**Pull request merged**
