### PR TITLE
Update vsc-extension-quickstart.md

### PR DESCRIPTION
**Pull request by suxstellino**
replaced "de" with "it", "German" with "Italian" and the localized name for ITA language.

### CODE REVIEW

**Comment by suxstellino** [comment]
Is this supposed to be just english, bilingual or only localised?

**Comment by danyeh** [comment]
bilingual would be great so that we can track the change and make sure consistency across languages without have to check with native speaker of each language. Thank you!

**Comment by suxstellino** [comment]
and what about the changelog? completely ita as I've just made?

**Comment by danyeh** [comment]
No worries. I can put English back. To be honest, the changelog and quickstart were in my to do list I haven't had time to look at. Thank you for pushing forward on this! We will continuous improve along the way.

**Pull request merged**
