### PR TITLE
fix zh-tw translation

### PR DESCRIPTION
**Pull request by lolikung**

### CODE REVIEW

**Comment by lukaschal** [comment]
On review.

File: vscode-extensions\merge-conflict.xlf
ID: 0; "extensions/merge-conflict/dist/mergeDecorator.currentChange"
SRC: (Current Change)
TGT: (当前更改)

**Comment by lukaschal** [comment]
Linguistic answer:

Current = 目前 is undoubtedly correct for CHT and TWN region.
當前 is for and from CHS and CHN region.

**Comment by lolikung** [comment]
```json
{
  "dist/codelensProvider": {
    "acceptCurrentChange": "接受當前變更"
  },
  "dist/commandHandler": {
    "compareChangesTitle": "{0}: 當前變更⟷來源變更"
 }
}
```
These two properties use "當前", so change "目前" of "dist/mergeDecorator.currentChange" property to "當前".

"目前" is more in line with TW region, or change other parts of this document from "當前" to "目前" ?

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
Fixed.

(目前變更)
{0}: 目前變更⟷ 即將到來的變更
接受目前變更

**Comment by weeteckt** [comment]
Closing since this is fixed.

**Pull request closed without merging**
