### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by coibaka**
Translate README.md to Vietnamese

### CODE REVIEW

**Comment by coibaka** [comment]
@microsoft-github-policy-service agree [company="{your company}"]
@microsoft-github-policy-service agree
@microsoft-github-policy-service agree company="Microsoft"

**Comment by coibaka** [comment]
@microsoft-github-policy-service agree [company="LearnToShare"]
@microsoft-github-policy-service agree
@microsoft-github-policy-service agree company="Microsoft"

**Comment by coibaka** [comment]
@microsoft-github-policy-service agree company="your company"

**Comment by coibaka** [comment]
@microsoft-github-policy-service agree company="LearnToShare"

**Comment by coibaka** [comment]
@microsoft-github-policy-service agree

**Comment by TylerLeonhardt** [comment]
We want to keep the main README in English.

**Pull request closed without merging**
