### PR TITLE
Fix for capitalize label in french and a missing space

### PR DESCRIPTION
**Pull request by nfon**
"Rename" & "Delete" contextual menu item in French are not capitalized.
A space is missing for trashFailed

### CODE REVIEW

**Comment by lukaschal** [comment]
Fixed as suggested in a MLCP platform.

**Comment by lukaschal** [comment]
@nfon Please verify and close this issue.

**Comment by nfon** [comment]
@lukaschal it's only partialy fixed: https://github.com/Microsoft/vscode-loc/blob/373fec463c88f44baa7fd0c879a916b05da9bb69/i18n/vscode-language-pack-fr/translations/main.i18n.json#L3669 'rename' is still not capitalize

**Comment by lukaschal** [comment]
Fixed now.

**Comment by nfon** [comment]
@lukaschal not seeing it but there may be a delay, I'll check later and open a new issue if needed. Thanks !

**Pull request closed without merging**
