### PR TITLE
Fix inconsistencies in german translation

### PR DESCRIPTION
**Pull request by pxlrbt**
Panel was inconsistently translated as "Bereich" or "Panel". Changed translations to "Panel" since "Bereich" is a very general term.

### CODE REVIEW

**Comment by lukaschal** [comment]
On review.

**Comment by lukaschal** [comment]
Translated consistently as "Panel" now.

**Comment by pxlrbt** [comment]
Sorry, found some more occurrences.

**Comment by lukaschal** [comment]
Implemented to MLCP as well.

**Pull request closed without merging**
